version: "3"
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bdb_development
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bdb
      - bundler-cache:/bundler
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      BACKEND_DATABASE_USER: rails
      BACKEND_DATABASE_PASSWORD: password
      BUNDLE_PATH: /bundler/vendor
volumes:
  postgres-data:
  bundler-cache:
